### ISSUE TITLE
"About Developer" section not created.

### ISSUE THREAD

**Issue by iAmPriyam** [jervis446/Dequinox.com#5]
A small icon (gear icon) is added in the footer with no links yet. The icon has to be linked with the "about developer " page.
Requirements:
i) The developer section should open as a modal in the page.
ii) It should contain the image, name and links to the respective Facebook, LinkedIn and git account.
iii) Background colour: #282828;
iv) Grayscale filter (100%) on the image.
v) Image should be circular.

**Comment by jervis446** [comment]
@iAmPriyam tu hi bana de

**Comment by iAmPriyam** [comment]
The developer section has been added.  ; )
